spring.application.name=ecommerce-backend

spring.datasource.url = jdbc:postgresql://localhost:5432/Ecommerce
spring.datasource.username=postgres
spring.datasource.password=Shivayya@7173
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

spring.web.resources.static-locations=file:Uploads/
jwt.secret=bXlzdXBlcnNlY3JldGtleW15c3VwZXJzZWNyZXRrZXkxMjM=
jwt.expiration=86400000


